### ISSUE TITLE
🛠 Set up comprehensive CI test scripts and pipeline

### ISSUE THREAD

**Issue by mamcisaac** [mamcisaac/teaching-engine2.0#253]
### Problem
Test scripts and CI pipeline need configuration for automated testing of the ETFO-aligned features.

#### Package.json Scripts
- [ ] Add to root `package.json`:
```json
{
  "scripts": {
    "test": "vitest run && pnpm -r test",
    "test:e2e": "playwright test",
    "test:coverage": "vitest run --coverage",
    "test:watch": "vitest watch"
  }
}
```

#### CI Pipeline Configuration
- [ ] Update `.github/workflows/test.yml` or equivalent:
```yaml
test:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      test-suite: [unit, integration, e2e]
  steps:
    - name: Run Backend Tests
      if: matrix.test-suite == 'unit' || matrix.test-suite == 'integration'
      run: pnpm test
    
    - name: Run E2E Tests
      if: matrix.test-suite == 'e2e'
      run: pnpm test:e2e
```

#### Coverage Requirements
- [ ] Set minimum coverage thresholds:
  - Statements: 80%
  - Branches: 75%
  - Functions: 80%
  - Lines: 80%

### Success Criteria
- All test commands work locally
- CI pipeline runs all test suites
- Failed tests block PR merges
- Coverage reports are generated and visible
